### ISSUE TITLE
Wrong default value ChrgBr

### ISSUE THREAD

**Issue by andre-m-dev** [viafintech/sps_king#6]
When a new `SPS::CreditTransfer` transaction is created, regardless of the value selected for `service_level`, `builder.ChrgBr('SLEV')` is always executed. According to the ISO manual, SLEV may only be used for SEPA payments.

<img width="930" alt="image" src="https://github.com/viafintech/sps_king/assets/1729839/e2fe43e1-6bc3-4128-8599-6a84a41d27b7">

Tested with ZKB in Switzerland

Code:
https://github.com/viafintech/sps_king/blob/b9db3101364836ceb07103041d3b5d0f6157b64d/lib/sps_king/message/credit_transfer.rb#L59

**Comment by tobischo** [comment]
Hi @andre-m-dev 
interestingly we have been using this for years without any issues or complaints for transfers within switzerland.

The service level currently only influences the service level code: https://github.com/viafintech/sps_king/blob/b9db3101364836ceb07103041d3b5d0f6157b64d/lib/sps_king/message/credit_transfer.rb#L34

So in my opinion, `service_level` should not directly affect the charge bearer.

We could make it optional to provide the value and use the provided charge bearer value instead of using the `SLEV` value.

**Comment by tobischo** [comment]
As per page 47:
https://www.six-group.com/dam/download/banking-services/standardization/sps/ig-credit-transfer-v2.0.2-de.pdf

![Bildschirmfoto 2024-07-03 um 13 52 40](https://github.com/viafintech/sps_king/assets/968947/03dd1954-ed5d-40fa-9576-5eb8d0ff7598)

So you are right, only for SEPA it must always be `SLEV`. I am wondering why it would be invalid in the general case though. Then again, we are always using an IBAN.

Could you maybe share a bit more information about your specific use case?

**Comment by andre-m-dev** [comment]
I created the transaction as follows:
```
sct.add_transaction(
  name:                   'XXX',
  bic:                    'ZKBKCHZZ80A',
  iban:                   'CHXXX',
  amount:                 2.00,
  currency:               'CHF',
  remittance_information: 'ACHTUNG TEST',
  batch_booking: false,
  instruction:            'InstrIDTEST',
  creditor_address: SPS::CreditorAddress.new(
    country_code:        'CH',
    street_name:         'XXX',
    building_number:     'XXX',
    post_code:           '8048',
    town_name:           'Zürich'
  )
)
```
and transmitted via: XE2. The technical support replied:
"In der Testdatei ist nach wie vor im B-Level der "falsche" Code für den Gebührenträger (Element "Charge Bearer") vorhanden (gelb markiert):
Gemäss dem ISO-Handbuch dürfte der Code SLEV nur für SEPA-Zahlungen verwendet werden:"

But maybe it's not the problem at all:
"Dieser Code wird aber offenbar von unserer Plausi-Prüfung ignoriert und lässt das File trotzdem durch. Abgesehen davon ist das File aber tiptop."

Hopefully this will help, otherwise you are welcome to get in touch by other ways.

**Comment by tobischo** [comment]
Ok, so here would be my proposal:
- let's make charge bearer a field that can be passed separately
- since it is technically an optional field, I would actually make it optional and not set it unless it is given
- add it as a very explicit mention in the release notes
- Since we are still in the 0.x versions, it would not result in a major version change

Would that solve your issue? On our side, I can take care of explicitly passing the field in the future so that nothing actually changes for our flow for now

**Comment by andre-m-dev** [comment]
@tobischo thank you very much for your effort and time. Based on the answer from technical support, I was just wondering why the attribute "ChrgBr" is always added with the value SLEV. The proposal looks good to me and I can test it afterwards.

**Comment by tobischo** [comment]
Pretty much because I may not have paid enough attention in the docs to the value being SEPA specific a few years ago 😄

**Comment by tobischo** [comment]
Alright, prepared a change in #7

Please let me know what you think
